plot4<-function(){
  plot4<-read.csv.sql(".\\power\\household_power_consumption.txt",sep = ";",sql = "select * from file where Date IN ('1/2/2007','2/2/2007')")
  dateTime<-paste(plot4$Date,plot4$Time)
  dateTime<-strptime(dateTime,format = "%d/%m/%Y %H:%M:%S")
  png("plot4.png", height = 480, width = 480, units = "px")
  par( mfrow = c( 2, 2 ))
  hist(plot4$Global_active_power,xlab=" ",ylab = "Global Active Power (kilowatts)", col="red", main=" ")
  plot(dateTime,plot4$Voltage,xlab="datetime",ylab="Voltage",type="n")
  lines(dateTime,plot4$Voltage)
  plot(dateTime,plot4$Sub_metering_1,type = "n", xlab=" ",ylab="Energy sub metering")
  lines(dateTime,plot4$Sub_metering_1)
  lines(dateTime,plot4$Sub_metering_2,col="red")
  lines(dateTime,plot4$Sub_metering_3,col="blue")
  legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=c(1,1,1))
  plot(dateTime,plot4$Global_reactive_power,xlab="datetime",ylab="Global_reactive_power",type = "n")
  lines(dateTime,plot4$Global_reactive_power)
  dev.off()
  }